// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ApplicationState string

const (
	ApplicationState_CREATING   ApplicationState = "CREATING"
	ApplicationState_CREATED    ApplicationState = "CREATED"
	ApplicationState_STARTING   ApplicationState = "STARTING"
	ApplicationState_STARTED    ApplicationState = "STARTED"
	ApplicationState_STOPPING   ApplicationState = "STOPPING"
	ApplicationState_STOPPED    ApplicationState = "STOPPED"
	ApplicationState_TERMINATED ApplicationState = "TERMINATED"
)

type Architecture string

const (
	Architecture_ARM64  Architecture = "ARM64"
	Architecture_X86_64 Architecture = "X86_64"
)

type JobRunMode string

const (
	JobRunMode_BATCH     JobRunMode = "BATCH"
	JobRunMode_STREAMING JobRunMode = "STREAMING"
)

type JobRunState string

const (
	JobRunState_SUBMITTED  JobRunState = "SUBMITTED"
	JobRunState_PENDING    JobRunState = "PENDING"
	JobRunState_SCHEDULED  JobRunState = "SCHEDULED"
	JobRunState_RUNNING    JobRunState = "RUNNING"
	JobRunState_SUCCESS    JobRunState = "SUCCESS"
	JobRunState_FAILED     JobRunState = "FAILED"
	JobRunState_CANCELLING JobRunState = "CANCELLING"
	JobRunState_CANCELLED  JobRunState = "CANCELLED"
	JobRunState_QUEUED     JobRunState = "QUEUED"
)
