//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
	if in.Architecture != nil {
		in, out := &in.Architecture, &out.Architecture
		*out = new(string)
		**out = **in
	}
	if in.AutoStartConfiguration != nil {
		in, out := &in.AutoStartConfiguration, &out.AutoStartConfiguration
		*out = new(AutoStartConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoStopConfiguration != nil {
		in, out := &in.AutoStopConfiguration, &out.AutoStopConfiguration
		*out = new(AutoStopConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientToken != nil {
		in, out := &in.ClientToken, &out.ClientToken
		*out = new(string)
		**out = **in
	}
	if in.DiskEncryptionConfiguration != nil {
		in, out := &in.DiskEncryptionConfiguration, &out.DiskEncryptionConfiguration
		*out = new(DiskEncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityCenterConfiguration != nil {
		in, out := &in.IdentityCenterConfiguration, &out.IdentityCenterConfiguration
		*out = new(IdentityCenterConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageConfiguration != nil {
		in, out := &in.ImageConfiguration, &out.ImageConfiguration
		*out = new(ImageConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialCapacity != nil {
		in, out := &in.InitialCapacity, &out.InitialCapacity
		*out = make(map[string]*InitialCapacityConfig, len(*in))
		for key, val := range *in {
			var outVal *InitialCapacityConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(InitialCapacityConfig)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.InteractiveConfiguration != nil {
		in, out := &in.InteractiveConfiguration, &out.InteractiveConfiguration
		*out = new(InteractiveConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.JobLevelCostAllocationConfiguration != nil {
		in, out := &in.JobLevelCostAllocationConfiguration, &out.JobLevelCostAllocationConfiguration
		*out = new(JobLevelCostAllocationConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MaximumCapacity != nil {
		in, out := &in.MaximumCapacity, &out.MaximumCapacity
		*out = new(MaximumAllowedResources)
		(*in).DeepCopyInto(*out)
	}
	if in.MonitoringConfiguration != nil {
		in, out := &in.MonitoringConfiguration, &out.MonitoringConfiguration
		*out = new(MonitoringConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = new(NetworkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseLabel != nil {
		in, out := &in.ReleaseLabel, &out.ReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.RuntimeConfiguration != nil {
		in, out := &in.RuntimeConfiguration, &out.RuntimeConfiguration
		*out = make([]*Configuration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Configuration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SchedulerConfiguration != nil {
		in, out := &in.SchedulerConfiguration, &out.SchedulerConfiguration
		*out = new(SchedulerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.WorkerTypeSpecifications != nil {
		in, out := &in.WorkerTypeSpecifications, &out.WorkerTypeSpecifications
		*out = make(map[string]*WorkerTypeSpecification, len(*in))
		for key, val := range *in {
			var outVal *WorkerTypeSpecification
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(WorkerTypeSpecification)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSummary) DeepCopyInto(out *ApplicationSummary) {
	*out = *in
	if in.Architecture != nil {
		in, out := &in.Architecture, &out.Architecture
		*out = new(string)
		**out = **in
	}
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ReleaseLabel != nil {
		in, out := &in.ReleaseLabel, &out.ReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StateDetails != nil {
		in, out := &in.StateDetails, &out.StateDetails
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSummary.
func (in *ApplicationSummary) DeepCopy() *ApplicationSummary {
	if in == nil {
		return nil
	}
	out := new(ApplicationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application_SDK) DeepCopyInto(out *Application_SDK) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.Architecture != nil {
		in, out := &in.Architecture, &out.Architecture
		*out = new(string)
		**out = **in
	}
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.AutoStartConfiguration != nil {
		in, out := &in.AutoStartConfiguration, &out.AutoStartConfiguration
		*out = new(AutoStartConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoStopConfiguration != nil {
		in, out := &in.AutoStopConfiguration, &out.AutoStopConfiguration
		*out = new(AutoStopConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.DiskEncryptionConfiguration != nil {
		in, out := &in.DiskEncryptionConfiguration, &out.DiskEncryptionConfiguration
		*out = new(DiskEncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityCenterConfiguration != nil {
		in, out := &in.IdentityCenterConfiguration, &out.IdentityCenterConfiguration
		*out = new(IdentityCenterConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageConfiguration != nil {
		in, out := &in.ImageConfiguration, &out.ImageConfiguration
		*out = new(ImageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialCapacity != nil {
		in, out := &in.InitialCapacity, &out.InitialCapacity
		*out = make(map[string]*InitialCapacityConfig, len(*in))
		for key, val := range *in {
			var outVal *InitialCapacityConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(InitialCapacityConfig)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.InteractiveConfiguration != nil {
		in, out := &in.InteractiveConfiguration, &out.InteractiveConfiguration
		*out = new(InteractiveConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.JobLevelCostAllocationConfiguration != nil {
		in, out := &in.JobLevelCostAllocationConfiguration, &out.JobLevelCostAllocationConfiguration
		*out = new(JobLevelCostAllocationConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MaximumCapacity != nil {
		in, out := &in.MaximumCapacity, &out.MaximumCapacity
		*out = new(MaximumAllowedResources)
		(*in).DeepCopyInto(*out)
	}
	if in.MonitoringConfiguration != nil {
		in, out := &in.MonitoringConfiguration, &out.MonitoringConfiguration
		*out = new(MonitoringConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = new(NetworkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseLabel != nil {
		in, out := &in.ReleaseLabel, &out.ReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.RuntimeConfiguration != nil {
		in, out := &in.RuntimeConfiguration, &out.RuntimeConfiguration
		*out = make([]*Configuration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Configuration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SchedulerConfiguration != nil {
		in, out := &in.SchedulerConfiguration, &out.SchedulerConfiguration
		*out = new(SchedulerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StateDetails != nil {
		in, out := &in.StateDetails, &out.StateDetails
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.WorkerTypeSpecifications != nil {
		in, out := &in.WorkerTypeSpecifications, &out.WorkerTypeSpecifications
		*out = make(map[string]*WorkerTypeSpecification, len(*in))
		for key, val := range *in {
			var outVal *WorkerTypeSpecification
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(WorkerTypeSpecification)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application_SDK.
func (in *Application_SDK) DeepCopy() *Application_SDK {
	if in == nil {
		return nil
	}
	out := new(Application_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoStartConfig) DeepCopyInto(out *AutoStartConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoStartConfig.
func (in *AutoStartConfig) DeepCopy() *AutoStartConfig {
	if in == nil {
		return nil
	}
	out := new(AutoStartConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoStopConfig) DeepCopyInto(out *AutoStopConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoStopConfig.
func (in *AutoStopConfig) DeepCopy() *AutoStopConfig {
	if in == nil {
		return nil
	}
	out := new(AutoStopConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchLoggingConfiguration) DeepCopyInto(out *CloudWatchLoggingConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyRef != nil {
		in, out := &in.EncryptionKeyRef, &out.EncryptionKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.LogGroupName != nil {
		in, out := &in.LogGroupName, &out.LogGroupName
		*out = new(string)
		**out = **in
	}
	if in.LogStreamNamePrefix != nil {
		in, out := &in.LogStreamNamePrefix, &out.LogStreamNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.LogTypes != nil {
		in, out := &in.LogTypes, &out.LogTypes
		*out = make(map[string][]*string, len(*in))
		for key, val := range *in {
			var outVal []*string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]*string, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(string)
						**out = **in
					}
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchLoggingConfiguration.
func (in *CloudWatchLoggingConfiguration) DeepCopy() *CloudWatchLoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(CloudWatchLoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationOverrides) DeepCopyInto(out *ConfigurationOverrides) {
	*out = *in
	if in.ApplicationConfiguration != nil {
		in, out := &in.ApplicationConfiguration, &out.ApplicationConfiguration
		*out = make([]*Configuration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Configuration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DiskEncryptionConfiguration != nil {
		in, out := &in.DiskEncryptionConfiguration, &out.DiskEncryptionConfiguration
		*out = new(DiskEncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MonitoringConfiguration != nil {
		in, out := &in.MonitoringConfiguration, &out.MonitoringConfiguration
		*out = new(MonitoringConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationOverrides.
func (in *ConfigurationOverrides) DeepCopy() *ConfigurationOverrides {
	if in == nil {
		return nil
	}
	out := new(ConfigurationOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskEncryptionConfiguration) DeepCopyInto(out *DiskEncryptionConfiguration) {
	*out = *in
	if in.EncryptionContext != nil {
		in, out := &in.EncryptionContext, &out.EncryptionContext
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyRef != nil {
		in, out := &in.EncryptionKeyRef, &out.EncryptionKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskEncryptionConfiguration.
func (in *DiskEncryptionConfiguration) DeepCopy() *DiskEncryptionConfiguration {
	if in == nil {
		return nil
	}
	out := new(DiskEncryptionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityCenterConfiguration) DeepCopyInto(out *IdentityCenterConfiguration) {
	*out = *in
	if in.IdentityCenterApplicationARN != nil {
		in, out := &in.IdentityCenterApplicationARN, &out.IdentityCenterApplicationARN
		*out = new(string)
		**out = **in
	}
	if in.IdentityCenterInstanceARN != nil {
		in, out := &in.IdentityCenterInstanceARN, &out.IdentityCenterInstanceARN
		*out = new(string)
		**out = **in
	}
	if in.UserBackgroundSessionsEnabled != nil {
		in, out := &in.UserBackgroundSessionsEnabled, &out.UserBackgroundSessionsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityCenterConfiguration.
func (in *IdentityCenterConfiguration) DeepCopy() *IdentityCenterConfiguration {
	if in == nil {
		return nil
	}
	out := new(IdentityCenterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityCenterConfigurationInput) DeepCopyInto(out *IdentityCenterConfigurationInput) {
	*out = *in
	if in.IdentityCenterInstanceARN != nil {
		in, out := &in.IdentityCenterInstanceARN, &out.IdentityCenterInstanceARN
		*out = new(string)
		**out = **in
	}
	if in.UserBackgroundSessionsEnabled != nil {
		in, out := &in.UserBackgroundSessionsEnabled, &out.UserBackgroundSessionsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityCenterConfigurationInput.
func (in *IdentityCenterConfigurationInput) DeepCopy() *IdentityCenterConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(IdentityCenterConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfiguration) DeepCopyInto(out *ImageConfiguration) {
	*out = *in
	if in.ImageURI != nil {
		in, out := &in.ImageURI, &out.ImageURI
		*out = new(string)
		**out = **in
	}
	if in.ResolvedImageDigest != nil {
		in, out := &in.ResolvedImageDigest, &out.ResolvedImageDigest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfiguration.
func (in *ImageConfiguration) DeepCopy() *ImageConfiguration {
	if in == nil {
		return nil
	}
	out := new(ImageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfigurationInput) DeepCopyInto(out *ImageConfigurationInput) {
	*out = *in
	if in.ImageURI != nil {
		in, out := &in.ImageURI, &out.ImageURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfigurationInput.
func (in *ImageConfigurationInput) DeepCopy() *ImageConfigurationInput {
	if in == nil {
		return nil
	}
	out := new(ImageConfigurationInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialCapacityConfig) DeepCopyInto(out *InitialCapacityConfig) {
	*out = *in
	if in.WorkerConfiguration != nil {
		in, out := &in.WorkerConfiguration, &out.WorkerConfiguration
		*out = new(WorkerResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerCount != nil {
		in, out := &in.WorkerCount, &out.WorkerCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialCapacityConfig.
func (in *InitialCapacityConfig) DeepCopy() *InitialCapacityConfig {
	if in == nil {
		return nil
	}
	out := new(InitialCapacityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InteractiveConfiguration) DeepCopyInto(out *InteractiveConfiguration) {
	*out = *in
	if in.LivyEndpointEnabled != nil {
		in, out := &in.LivyEndpointEnabled, &out.LivyEndpointEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StudioEnabled != nil {
		in, out := &in.StudioEnabled, &out.StudioEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InteractiveConfiguration.
func (in *InteractiveConfiguration) DeepCopy() *InteractiveConfiguration {
	if in == nil {
		return nil
	}
	out := new(InteractiveConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobLevelCostAllocationConfiguration) DeepCopyInto(out *JobLevelCostAllocationConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobLevelCostAllocationConfiguration.
func (in *JobLevelCostAllocationConfiguration) DeepCopy() *JobLevelCostAllocationConfiguration {
	if in == nil {
		return nil
	}
	out := new(JobLevelCostAllocationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobRun) DeepCopyInto(out *JobRun) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.AttemptCreatedAt != nil {
		in, out := &in.AttemptCreatedAt, &out.AttemptCreatedAt
		*out = (*in).DeepCopy()
	}
	if in.AttemptUpdatedAt != nil {
		in, out := &in.AttemptUpdatedAt, &out.AttemptUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.EndedAt != nil {
		in, out := &in.EndedAt, &out.EndedAt
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = new(NetworkConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseLabel != nil {
		in, out := &in.ReleaseLabel, &out.ReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.StateDetails != nil {
		in, out := &in.StateDetails, &out.StateDetails
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TotalExecutionDurationSeconds != nil {
		in, out := &in.TotalExecutionDurationSeconds, &out.TotalExecutionDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobRun.
func (in *JobRun) DeepCopy() *JobRun {
	if in == nil {
		return nil
	}
	out := new(JobRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobRunAttemptSummary) DeepCopyInto(out *JobRunAttemptSummary) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.JobCreatedAt != nil {
		in, out := &in.JobCreatedAt, &out.JobCreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ReleaseLabel != nil {
		in, out := &in.ReleaseLabel, &out.ReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.StateDetails != nil {
		in, out := &in.StateDetails, &out.StateDetails
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobRunAttemptSummary.
func (in *JobRunAttemptSummary) DeepCopy() *JobRunAttemptSummary {
	if in == nil {
		return nil
	}
	out := new(JobRunAttemptSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobRunSummary) DeepCopyInto(out *JobRunSummary) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.AttemptCreatedAt != nil {
		in, out := &in.AttemptCreatedAt, &out.AttemptCreatedAt
		*out = (*in).DeepCopy()
	}
	if in.AttemptUpdatedAt != nil {
		in, out := &in.AttemptUpdatedAt, &out.AttemptUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ReleaseLabel != nil {
		in, out := &in.ReleaseLabel, &out.ReleaseLabel
		*out = new(string)
		**out = **in
	}
	if in.StateDetails != nil {
		in, out := &in.StateDetails, &out.StateDetails
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobRunSummary.
func (in *JobRunSummary) DeepCopy() *JobRunSummary {
	if in == nil {
		return nil
	}
	out := new(JobRunSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPersistenceMonitoringConfiguration) DeepCopyInto(out *ManagedPersistenceMonitoringConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyRef != nil {
		in, out := &in.EncryptionKeyRef, &out.EncryptionKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPersistenceMonitoringConfiguration.
func (in *ManagedPersistenceMonitoringConfiguration) DeepCopy() *ManagedPersistenceMonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(ManagedPersistenceMonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaximumAllowedResources) DeepCopyInto(out *MaximumAllowedResources) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaximumAllowedResources.
func (in *MaximumAllowedResources) DeepCopy() *MaximumAllowedResources {
	if in == nil {
		return nil
	}
	out := new(MaximumAllowedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfiguration) DeepCopyInto(out *MonitoringConfiguration) {
	*out = *in
	if in.CloudWatchLoggingConfiguration != nil {
		in, out := &in.CloudWatchLoggingConfiguration, &out.CloudWatchLoggingConfiguration
		*out = new(CloudWatchLoggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagedPersistenceMonitoringConfiguration != nil {
		in, out := &in.ManagedPersistenceMonitoringConfiguration, &out.ManagedPersistenceMonitoringConfiguration
		*out = new(ManagedPersistenceMonitoringConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PrometheusMonitoringConfiguration != nil {
		in, out := &in.PrometheusMonitoringConfiguration, &out.PrometheusMonitoringConfiguration
		*out = new(PrometheusMonitoringConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.S3MonitoringConfiguration != nil {
		in, out := &in.S3MonitoringConfiguration, &out.S3MonitoringConfiguration
		*out = new(S3MonitoringConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfiguration.
func (in *MonitoringConfiguration) DeepCopy() *MonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfiguration) DeepCopyInto(out *NetworkConfiguration) {
	*out = *in
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SecurityGroupRefs != nil {
		in, out := &in.SecurityGroupRefs, &out.SecurityGroupRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SubnetRefs != nil {
		in, out := &in.SubnetRefs, &out.SubnetRefs
		*out = make([]*corev1alpha1.AWSResourceReferenceWrapper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.AWSResourceReferenceWrapper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfiguration.
func (in *NetworkConfiguration) DeepCopy() *NetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(NetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusMonitoringConfiguration) DeepCopyInto(out *PrometheusMonitoringConfiguration) {
	*out = *in
	if in.RemoteWriteURL != nil {
		in, out := &in.RemoteWriteURL, &out.RemoteWriteURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusMonitoringConfiguration.
func (in *PrometheusMonitoringConfiguration) DeepCopy() *PrometheusMonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(PrometheusMonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	if in.MaxFailedAttemptsPerHour != nil {
		in, out := &in.MaxFailedAttemptsPerHour, &out.MaxFailedAttemptsPerHour
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3MonitoringConfiguration) DeepCopyInto(out *S3MonitoringConfiguration) {
	*out = *in
	if in.EncryptionKeyARN != nil {
		in, out := &in.EncryptionKeyARN, &out.EncryptionKeyARN
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKeyRef != nil {
		in, out := &in.EncryptionKeyRef, &out.EncryptionKeyRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.LogURI != nil {
		in, out := &in.LogURI, &out.LogURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3MonitoringConfiguration.
func (in *S3MonitoringConfiguration) DeepCopy() *S3MonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(S3MonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerConfiguration) DeepCopyInto(out *SchedulerConfiguration) {
	*out = *in
	if in.MaxConcurrentRuns != nil {
		in, out := &in.MaxConcurrentRuns, &out.MaxConcurrentRuns
		*out = new(int64)
		**out = **in
	}
	if in.QueueTimeoutMinutes != nil {
		in, out := &in.QueueTimeoutMinutes, &out.QueueTimeoutMinutes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerConfiguration.
func (in *SchedulerConfiguration) DeepCopy() *SchedulerConfiguration {
	if in == nil {
		return nil
	}
	out := new(SchedulerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerResourceConfig) DeepCopyInto(out *WorkerResourceConfig) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(string)
		**out = **in
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerResourceConfig.
func (in *WorkerResourceConfig) DeepCopy() *WorkerResourceConfig {
	if in == nil {
		return nil
	}
	out := new(WorkerResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerTypeSpecification) DeepCopyInto(out *WorkerTypeSpecification) {
	*out = *in
	if in.ImageConfiguration != nil {
		in, out := &in.ImageConfiguration, &out.ImageConfiguration
		*out = new(ImageConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerTypeSpecification.
func (in *WorkerTypeSpecification) DeepCopy() *WorkerTypeSpecification {
	if in == nil {
		return nil
	}
	out := new(WorkerTypeSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerTypeSpecificationInput) DeepCopyInto(out *WorkerTypeSpecificationInput) {
	*out = *in
	if in.ImageConfiguration != nil {
		in, out := &in.ImageConfiguration, &out.ImageConfiguration
		*out = new(ImageConfigurationInput)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerTypeSpecificationInput.
func (in *WorkerTypeSpecificationInput) DeepCopy() *WorkerTypeSpecificationInput {
	if in == nil {
		return nil
	}
	out := new(WorkerTypeSpecificationInput)
	in.DeepCopyInto(out)
	return out
}
